package pojo;

// Generated 15 May, 2015 10:26:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * Checkpoint generated by hbm2java
 */
public class Checkpoint implements java.io.Serializable {

	private Integer sno;
	private String journalId;
	private String articleId;
	private String dataset;
	private String MetaXMLName;
	private String zipfileName;
	private int status;

	public Checkpoint() {
	}

	public Checkpoint(String journalId, String articleId, String dataset,
			String zipfileName, int status, String metaXMLName) {
		this.journalId = journalId;
		this.articleId = articleId;
		this.dataset = dataset;		
		this.zipfileName = zipfileName;
		this.status=status;
		MetaXMLName=metaXMLName;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public String getJournalId() {
		return this.journalId;
	}

	public void setJournalId(String journalId) {
		this.journalId = journalId;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getDataset() {
		return this.dataset;
	}

	public String getMetaXMLName() {
		return MetaXMLName;
	}

	public void setMetaXMLName(String metaXMLName) {
		MetaXMLName = metaXMLName;
	}
	
	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	public String getZipfileName() {
		return this.zipfileName;
	}

	public void setZipfileName(String zipfileName) {
		this.zipfileName = zipfileName;
	}
	
	public void setStatus(int status) {
		this.status=status;
	}
	
	public int getStatus() {
		return this.status;
	}
	

}
