package pojo;

// Generated 4 May, 2015 11:32:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
/**
 * Datasetstatus generated by hbm2java
 */
public class Datasetstatus implements java.io.Serializable {

	private Integer datasetStatusId;
	private int supplierId;
	private String datasetId;	
	private String journalId;
	private String articleId;
	private String ArticleTitle;
	private String metaXMLName;
	private DatasetenumStatus status;
	private Date downloadPickUpTime;
	private Date startDate;
	private Date endDate;
	private Datasethistory datasetHistory;
	
	public Datasethistory getDatasetHistory() {
		return datasetHistory;
	}

	public void setDatasetHistory(Datasethistory datasetHistory) {
		this.datasetHistory = datasetHistory;
	}
	
	public Datasetstatus() {
		
	}
	
	public enum status {
		 MALE, FEMALE
	}
	
	@Enumerated(EnumType.STRING)
	public DatasetenumStatus getStatus() {
		return this.status;
	}
	

	public Datasetstatus(int supplierId, String datasetId, DatasetenumStatus status) {
		this.supplierId = supplierId;
		this.datasetId = datasetId;
		this.status = status;
	}

	public Datasetstatus(int supplierId, String datasetId, DatasetenumStatus status,
			Date downloadPickUpTime, Date startDate, Date endDate) {
		this.supplierId = supplierId;
		this.datasetId = datasetId;
		this.status = status;
		this.downloadPickUpTime = downloadPickUpTime;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Integer getDatasetStatusId() {
		return this.datasetStatusId;
	}

	public void setDatasetStatusId(Integer datasetStatusId) {
		this.datasetStatusId = datasetStatusId;
	}

	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	public String getDatasetId() {
		return this.datasetId;
	}

	public void setDatasetId(String datasetId) {
		this.datasetId = datasetId;
	}

	public void setJournalId(String journalId) {
		this.journalId=journalId;
	}
	
	public String getJournalId() {
		return journalId;
	}
	
	public String getArticleId() {
		return articleId;
	}

	public String getArticleTitle() {
		return ArticleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		ArticleTitle = articleTitle;
	}
	
	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public void setStatus(DatasetenumStatus status) {
		this.status = status;
	}
	public String getMetaXMLName() {
		return metaXMLName;
	}

	public void setMetaXMLName(String metaXMLName) {
		this.metaXMLName = metaXMLName;
	}

	public Date getDownloadPickUpTime() {
		return this.downloadPickUpTime;
	}

	public void setDownloadPickUpTime(Date downloadPickUpTime) {
		this.downloadPickUpTime = downloadPickUpTime;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
