package pojo;

// Generated 8 May, 2015 9:54:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Datasethistory generated by hbm2java
 */
public class Datasethistory implements java.io.Serializable {

	private Integer sno;
	private Datasetstatus datasetstatus;
	private String message;
	private String Datasetid;	
	private String stage;
	private Date processTime;

	public Datasethistory() {
	}

	public Datasethistory(Datasetstatus datasetstatus) {
		this.datasetstatus = datasetstatus;
	}

	public Datasethistory(Datasetstatus datasetstatus, String message,
			Date processTime, String stage, String Datasetid) {
		this.datasetstatus = datasetstatus;
		this.message = message;
		this.processTime = processTime;
		this.stage=stage;
		this.Datasetid=Datasetid;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public Datasetstatus getDatasetstatus() {
		return this.datasetstatus;
	}

	public void setDatasetstatus(Datasetstatus datasetstatus) {
		this.datasetstatus = datasetstatus;
	}
	
	public String getDatasetid() {
		return Datasetid;
	}

	public void setDatasetid(String datasetid) {
		Datasetid = datasetid;
	}
	
	public String getStage() {
		return stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Date processTime) {
		this.processTime = processTime;
	}

}
